id: P00B0CAD7
initial_creation_type: ocr
source_metadata:
  volumes:
    32346bc3fa274fb7a45ab04586dcf0ac:
      base_file: v062.txt
      image_group_id: I1PD95907
      title: དབུ་མ་རྒྱན་གྱི་ཚིག་ལེའུར་བྱས་པ།
      total_pages: 1557
      volume_number: 62
